### ISSUE TITLE
First commit of Milano's analysis code

### ISSUE THREAD

**Issue by cmsromadaq** [I-MCP/BTF_TB_SW#1]

**Comment by cmsromadaq** [comment]
@simoneg90: closing an issue means that the task has to be completed... not that you closes on your laptop ;)

**Comment by simoneg90** [comment]
@cmromadaq, ops! sorry...

**Comment by cmsromadaq** [comment]
Starting to put together in the master the skeleton analysis class and the Makefile

**Comment by cmsromadaq** [comment]
The skeleton is evolving
